/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesawat;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jabbar Bie
 */
public class FormPesan_Tiket extends javax.swing.JFrame {

    /**
     * Creates new form FormPesan_Tiket
     */
    String[] kota   = {"Surabaya", "Jakarta", "Bandung", "Bali", "Banjarmasin"};
    
    public void setAsal(){
        DefaultComboBoxModel asal = new DefaultComboBoxModel(kota);
        cbAsal.setModel(asal);
    }
    public void setTujuan(Integer asal){
        cbTujuan.removeAllItems();
        String[] tujuan ; 
        for (int i = 0, x = 0; i < kota.length; i++) {
            if(i == asal){
                continue;
            }
            cbTujuan.addItem(kota[i]);
        }
    }
    public FormPesan_Tiket() {
        initComponents();
        setAsal();
        
    }
    public void hapus_isitable(){
//        DefaultTableModel modelx = (DefaultTableModel)JTableTiket.getModel();
//        for (int i = 0; i < model.getRowCount() - 1; i++) {
//            model.removeRow(i);
//        }
//        modelx.setRowCount(0);
    }
    public void data_tiket(String asal, String tujuan){
        hapus_isitable();
//      String[][] data = {
//            {"Jakarta","Surabaya","Pagi","07:00", "850000"},
//            {"Jakarta","Surabaya","Pagi","07:00", "950000"},
//            {"Jakarta","Surabaya","Pagi","07:00", "750000"},
//            {"Jakarta","Surabaya","Pagi","07:00", "650000"},
//            
//        };
        String[][] data;
        String[] Waktu = {"Pagi", "Siang", "Malam"};
        String[] Pukul = {"07:00", "11.45", "18:30"};
        int[] Harga = {850000,990000,1100000};
        DefaultTableModel model = (DefaultTableModel)JTableTiket.getModel();
        model.setRowCount(0);
        for (int i = 0; i < 3; i++) {
//            model.removeRow(i);
            model.addRow( new Object[] {asal, tujuan, Waktu[i], Pukul[i], Integer.toString(Harga[i]) });
        }
//        for(String[] row : data){
//            model.addRow(row);
//        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableTiket = new javax.swing.JTable();
        txtTest = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAsal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbTujuan = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Asal", "Tujuan", "Waktu", "Pukul", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableTiket.setColumnSelectionAllowed(true);
        JTableTiket.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        JTableTiket.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JTableTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableTiketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableTiket);
        JTableTiket.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (JTableTiket.getColumnModel().getColumnCount() > 0) {
            JTableTiket.getColumnModel().getColumn(0).setResizable(false);
            JTableTiket.getColumnModel().getColumn(1).setResizable(false);
            JTableTiket.getColumnModel().getColumn(2).setResizable(false);
            JTableTiket.getColumnModel().getColumn(3).setResizable(false);
            JTableTiket.getColumnModel().getColumn(4).setResizable(false);
        }

        txtTest.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTest.setText("Pilih Tujuan Penerbangan");

        jLabel2.setText("Asal ");

        cbAsal.setToolTipText("Pilih Kota tujuan anda");
        cbAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAsalActionPerformed(evt);
            }
        });

        jLabel3.setText("Tujuan");

        cbTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTujuanActionPerformed(evt);
            }
        });

        btnSimpan.setText("Pesan");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(txtTest))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCari)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbAsal, 0, 137, Short.MAX_VALUE)
                                        .addComponent(cbTujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTest)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCari)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String[] pilihtiket = new String[10];
        int baris = JTableTiket.getSelectedRow();
        for (int i = 0; i < 5; i++) {
            pilihtiket[i]    = JTableTiket.getModel().getValueAt(baris, i).toString();
        }
        
        new FormPesan(pilihtiket).setVisible(true);
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cbAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAsalActionPerformed
        // TODO add your handling code here:
        Integer asal = cbAsal.getSelectedIndex();
        if (asal > -1){
//            cbTujuan.removeItemAt(asal);
//            asal;
            setTujuan(asal);
        }
    }//GEN-LAST:event_cbAsalActionPerformed

    private void cbTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTujuanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTujuanActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        data_tiket(cbAsal.getSelectedItem().toString(), cbTujuan.getSelectedItem().toString());
    }//GEN-LAST:event_btnCariActionPerformed

    private void JTableTiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableTiketMouseClicked
        // TODO add your handling code here:
        btnSimpan.setEnabled(true);
    }//GEN-LAST:event_JTableTiketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesan_Tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableTiket;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbAsal;
    private javax.swing.JComboBox<String> cbTujuan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtTest;
    // End of variables declaration//GEN-END:variables
}
